# Generated by Django 4.2.1 on 2024-12-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graphic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Graphic', models.CharField(max_length=255)),
                ('additional', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technical_staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical', models.CharField(max_length=255)),
            ],
        ),
    ]
