# Generated by Django 4.2.1 on 2025-01-03 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('designation', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_no', models.CharField(max_length=100)),
                ('quotation_date', models.DateField()),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.TextField()),
                ('company_gst_no', models.CharField(max_length=50)),
                ('gst', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('quotation_validity', models.CharField(max_length=255)),
                ('gst_number', models.CharField(max_length=50)),
                ('pan_number', models.CharField(max_length=50)),
                ('delivery_schedule', models.CharField(max_length=255)),
                ('additional_info', models.TextField()),
            ],
            options={
                'db_table': 'quotation',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('scope_of_work', models.TextField()),
                ('scope_of_work_image', models.ImageField(blank=True, null=True, upload_to='scope_of_work_images/')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('hsn_code', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('cost_per_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='business.quotation')),
            ],
            options={
                'db_table': 'quotationdetails',
            },
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_terms', to='business.quotation')),
            ],
            options={
                'db_table': 'paymentterm',
            },
        ),
        migrations.CreateModel(
            name='OtherTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_terms', to='business.quotation')),
            ],
            options={
                'db_table': 'otherterm',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_ref_no', models.CharField(max_length=50)),
                ('agenda', models.TextField()),
                ('minutes_of_meeting', models.TextField(blank=True, null=True)),
                ('date_time', models.DateTimeField()),
                ('department', models.CharField(max_length=100)),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('attendees', models.ManyToManyField(related_name='meetings', to='business.meetingattendee')),
            ],
        ),
    ]
