# Generated by Django 4.2.1 on 2025-01-03 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_meetingattendee_quotation_workorder_quotationdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphic',
            name='enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graphics', to='business.meeting'),
        ),
    ]
