# Generated by Django 4.2.1 on 2025-01-03 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_graphic_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='technical_staff',
            name='enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technical_staff', to='business.meeting'),
        ),
    ]
