# Generated by Django 4.2.1 on 2025-01-04 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_technical_staff_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphic',
            name='enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graphic_designs', to='business.meeting'),
        ),
        migrations.AlterField(
            model_name='technical_staff',
            name='enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technical_staffing', to='business.meeting'),
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_services', models.TextField(blank=True, null=True)),
                ('design_and_development', models.TextField(blank=True, null=True)),
                ('software_design_and_dev_engineering_analysis', models.TextField(blank=True, null=True)),
                ('manufacturing', models.TextField(blank=True, null=True)),
                ('fabrication', models.TextField(blank=True, null=True)),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='business.meeting')),
            ],
        ),
    ]
