# Generated by Django 4.2.1 on 2025-01-06 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_graphic_enquiry_alter_technical_staff_enquiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='enquiry_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='business.meeting'),
        ),
    ]
