# Generated by Django 4.2.1 on 2025-01-17 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_enquiry'),
        ('business', '0007_enquiry_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.client'),
        ),
    ]
