# Generated by Django 4.2.1 on 2025-01-19 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_enquiry'),
        ('business', '0008_meeting_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.client'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workorder', to='business.meeting'),
        ),
    ]
