# Generated by Django 4.2.1 on 2025-01-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_workorder_client_workorder_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='scope_of_work_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/scope_of_work_images/'),
        ),
    ]
