# Generated by Django 4.2.1 on 2025-01-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_alter_workorder_scope_of_work_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='scope_of_work_image',
            field=models.ImageField(blank=True, null=True, upload_to='scope_of_work_images/'),
        ),
    ]
