# Generated by Django 4.2.1 on 2025-01-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Dr.', 'Dr.')], default='Mr.', max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('college_name', models.CharField(max_length=255)),
                ('year_of_grad', models.IntegerField()),
                ('degree', models.CharField(max_length=100)),
                ('stream', models.CharField(max_length=100)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current_company', models.BooleanField(default=False)),
                ('work_exp', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('company_loc', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobid', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('experience', models.CharField(default=0, max_length=10)),
                ('salary', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('application_deadline', models.DateField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
