# Generated by Django 4.2.1 on 2025-01-17 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_interview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortlistedApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortlisted_date', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job.applicant')),
            ],
        ),
    ]
