# Generated by Django 4.2.1 on 2025-01-20 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_shortlistedapplicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='candidate_name',
        ),
        migrations.AddField(
            model_name='interview',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='job.applicant'),
        ),
    ]
