# Generated by Django 4.2.1 on 2025-01-20 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_remove_interview_candidate_name_interview_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='candidate',
        ),
        migrations.AddField(
            model_name='interview',
            name='applicant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.applicant'),
        ),
    ]
