# Generated by Django 4.2.1 on 2025-01-20 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_remove_interview_applicant_interview_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortlistedapplicant',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='shortlistedapplicant',
            name='shortlisted_date',
        ),
        migrations.AddField(
            model_name='shortlistedapplicant',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_applicants', to='job.applicant'),
        ),
        migrations.AddField(
            model_name='shortlistedapplicant',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_shortlisted_applicants', to='job.interview'),
        ),
        migrations.AddField(
            model_name='shortlistedapplicant',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_shortlisted_applicants', to='job.interview'),
        ),
    ]
