# Generated by Django 4.2.1 on 2025-01-20 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_remove_shortlistedapplicant_applicant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortlistedapplicant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='shortlistedapplicant',
            name='position',
        ),
        migrations.AddField(
            model_name='shortlistedapplicant',
            name='interview',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_applicants', to='job.interview'),
        ),
    ]
