# Generated by Django 4.2.1 on 2025-01-20 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_remove_shortlistedapplicant_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='job.job'),
        ),
    ]
