# Generated by Django 4.2.1 on 2025-01-19 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_enquiry'),
        ('technical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalform',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.client'),
        ),
    ]
